service:
  apm:
    enabled: false
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: ""
  containers:
    cmenv:
    - name: API_URL
      cmkey: external.url
      cmname: landscape-config
      nsSuffix: true
