service:
  apm:
    enabled: false
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: ""
  deployment:
    customannotations:
      vault.hashicorp.com/role: qa-intcloud-apigw
      vault.hashicorp.com/agent-inject-secret-apim-designer-service-secret.properties:  kv/data/qa/intcloud/apigw/common/aws-iicsqa-intcloud-apigwqarel-eks-qa-usw2/apigw-qa-rel/serviceResource/RDBMS/apic-designer/main/system/user/active
      vault.hashicorp.com/secret-volume-path-apim-designer-service-secret.properties: /opt/tomcat/config/
      vault.hashicorp.com/agent-inject-template-apim-designer-service-secret.properties: |
        {{- with secret "kv/data/qa/intcloud/apigw/common/aws-iicsqa-intcloud-apigwqarel-eks-qa-usw2/apigw-qa-rel/serviceResource/RDBMS/apic-designer/main/system/user/active" }}
        {{- range $k, $v := .Data.data }}
        {{$k}}={{$v}}
        {{- end }}
        {{- end }}
    vault: true
